services:
  pg_local:
    image: postgres:14.4-alpine
    container_name: pg-local-container
    # restart: always
    environment:
      - POSTGRES_DB=pg-local-db
      - POSTGRES_USER=pg-local-user
      - POSTGRES_PASSWORD=pg-local-password
    ports:
      - 5432:5432
    volumes:
      - pg-local-volume:/var/lib/postgresql/data
      - ./src/postgres/etc/:/docker-entrypoint-initdb.d/

volumes:
  pg-local-volume:
    driver: local